// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5-tM8_-MFJxaOXdayUajOX0vsR3UZqQ',
    appId: '1:868123114953:web:ca4718e29356fb0383bc18',
    messagingSenderId: '868123114953',
    projectId: 'flutter-delivery-app-ee0ca',
    authDomain: 'flutter-delivery-app-ee0ca.firebaseapp.com',
    storageBucket: 'flutter-delivery-app-ee0ca.appspot.com',
    measurementId: 'G-CQ1FTJMT8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykXYT_UvVNgG6p_Z_KxrrqRKvqtZHN9k',
    appId: '1:868123114953:android:cbc52db5aae52f5b83bc18',
    messagingSenderId: '868123114953',
    projectId: 'flutter-delivery-app-ee0ca',
    storageBucket: 'flutter-delivery-app-ee0ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBmDLz2PlYR2egUWNc5jJ3BwvANrkwd0',
    appId: '1:868123114953:ios:ca465826d57d9f0e83bc18',
    messagingSenderId: '868123114953',
    projectId: 'flutter-delivery-app-ee0ca',
    storageBucket: 'flutter-delivery-app-ee0ca.appspot.com',
    iosClientId: '868123114953-kkq4hloietgqts9t7fnnu18ejh2rse5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBmDLz2PlYR2egUWNc5jJ3BwvANrkwd0',
    appId: '1:868123114953:ios:049552d34d5c099783bc18',
    messagingSenderId: '868123114953',
    projectId: 'flutter-delivery-app-ee0ca',
    storageBucket: 'flutter-delivery-app-ee0ca.appspot.com',
    iosClientId: '868123114953-o6jba0q23mvips0r306j5v7pvi4aun69.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryapp.RunnerTests',
  );
}
